language: node_js
cache:
  directories:
    - ~/.npm
email:
    recipients:
      - jae.b.bradley@gmail.com
    on_success: always
    on_failure: always
node_js:
  - '9'
  - '8'
  - '6'
  - '4'
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
