language: node_js
node_js:
  - '9'
  - '8'
  - '6'
cache:
  directories:
    - ~/.npm
notifications:
  email:
    recipients:
      - jae.b.bradley@gmail.com
    on_success: always
    on_failure: always
env:
  - BUILD_LEADER_ID=6
stages:
  - lint
  - compile
  - test
jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: compile
      script: npm run compile
    - stage: test
      script: npm run test
      script: npm run coverage && npm run coveralls
      after_success: npm run semantic-release
  on:
    branch: master
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
