language: node_js
node_js:
  - '9'
  - '8'
  - '6'
cache:
  directories:
    - ~/.npm
notifications:
  email:
    recipients:
      - jae.b.bradley@gmail.com
    on_success: always
    on_failure: always
stages:
  - lint
  - compile
  - coverage
  - deploy
jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: compile
      script: npm run compile
    - stage: test
      script: npm run test
    - stage: coverage
      script: npm run coveralls
    - stage: deploy
      script: npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
